DROP TABLE IF EXISTS Player_Team_Performance_Fact;
CREATE TABLE Player_Team_Performance_Fact(
	player_key INT,
	match_key INT,
	team_key INT,
	opponent_team_key INT,
	minutes_played INT,
	goals INT,
	assists INT,
	own_goals INT,
	pens_made INT,
    	pens_att INT,
	total_shots INT,
	shots_on_target INT,
	total_passes INT,
	completed_passes INT,
	completed_pass_percentage FLOAT,
	progressive_passes INT,
	carries INT,
	progressive_carries INT,
	take_ons INT,
	take_ons_won INT,
	yellow_cards INT, 
	red_cards INT,
	touches INT, 
	tackles INT, 
	interceptions INT,
	blocks INT,
	xg FLOAT,
	non_penality_xg FLOAT,
	xg_assist FLOAT,
	shot_creating_actions INT,
	goal_creating_actions INT
	PRIMARY KEY(player_key, match_key),
	FOREIGN KEY(player_key) REFERENCES Dim_player(player_key),
	FOREIGN KEY(match_key) REFERENCES Dim_match(match_key),
	FOREIGN KEY(team_key) REFERENCES Dim_team(team_key),
	FOREIGN KEY(opponent_team_key) REFERENCES Dim_team(team_key)
)
